include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_redundant_argument_values
    - always_use_package_imports
    - cascade_invocations
    - combinators_ordering
    - directives_ordering
    - eol_at_end_of_file
    - lines_longer_than_80_chars
    - noop_primitive_operations
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_foreach
    - prefer_single_quotes
    - sort_pub_dependencies
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_null_aware_elements
    - use_raw_strings
    - use_test_throws_matchers
    - use_truncating_division
