name: fernet
description: A Dart library for encrypting and decrypting messages using the Fernet scheme.
version: 0.0.7
repository: https://github.com/elliotwutingfeng/fernet
funding:
  - https://www.buymeacoffee.com/elliotwutingfeng
topics:
  - crypto
  - cryptography
  - encryption
  - security

environment:
  sdk: ^3.13.0

dependencies:
  cipherlib: ^0.7.2

dev_dependencies:
  coverage: ^1.15.1
  lints: ^6.1.0
  test: ^1.32.0
